=== wxw890/XmlApp/ex04.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ENTITY KR "대한민국">
<!ENTITY FR "프랑스">
<!ENTITY US "미국">

<!ELEMENT booklist (book*)>
	<!ELEMENT book (title, author, nation)>
		<!ELEMENT title (#PCDATA)>
		<!ELEMENT author (#PCDATA)>
		<!ELEMENT nation (#PCDATA)>
		
<!ATTLIST book nation ENTITY #IMPLIED>

=== wxw890/XmlApp/ex04.xml
<?xml version="1.0" encoding="UTF-8"?><!-- 프롤로그 -->
<!DOCTYPE book SYSTEM "ex04.dtd"><!--DOCTYPE이란 설계도를 참조할때 사용한다. 즉, ex02.dtd을 참조한다.  -->
<booklist><!-- 엘리먼트 -->
	<book >
	<title>노인과 바다</title><!-- 설계도의 순서와 태그 이름 모두 같아야한다. -->
	<author nation="&us;">헤밍웨이</author>
	<nation></nation>
	</book>
	<book >
	<title>노인과 바다2</title><!-- 설계도의 순서와 태그 이름 모두 같아야한다. -->
	<author nation="&kr;">헤밍웨이2</author>
	<nation></nation>
	</book>
</booklist>
